# Generated by Django 4.2.7 on 2026-04-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Detailed Answer', 'verbose_name_plural': 'Detailed Answers'},
        ),
    ]
