# Generated by Django 4.2.7 on 2026-05-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_answer_options_candidate_is_activated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
    ]
