# Generated by Django 4.2.7 on 2026-05-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_candidate_is_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(default=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('passing_percentage', models.IntegerField(default=50)),
                ('min_selection_score', models.IntegerField(default=60)),
                ('total_questions', models.IntegerField(default=20)),
                ('max_attempts', models.IntegerField(default=1)),
                ('show_answers', models.BooleanField(default=True)),
            ],
        ),
    ]
