# Generated by Django 4.2.7 on 2026-05-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_category_examsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examsetting',
            name='results_published',
            field=models.BooleanField(default=True),
        ),
    ]
