# Generated by Django 4.2.7 on 2026-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_notification_supportquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assigned_candidates',
            field=models.ManyToManyField(blank=True, related_name='assigned_exams', to='exam.candidate'),
        ),
        migrations.AddField(
            model_name='exam',
            name='negative_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='exams', to='exam.category'),
        ),
    ]
