# Generated by Django 4.2.7 on 2026-05-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_exam_assigned_candidates_exam_negative_marking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('registration_id', models.CharField(max_length=50, unique=True)),
                ('reason', models.TextField(blank=True, help_text='Why they need access', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Pending Registration',
                'verbose_name_plural': 'Pending Registrations',
                'ordering': ['-requested_at'],
            },
        ),
    ]
